###
### Trident One Config Params
### Specifies dimensions of vehicle for real-world control.
###

# note that the base link of the vehicle is defined as the
# center of the rear axle
# -- none of these measurements rely on that though :)
/**:
  ros__parameters:
    wheel_radius: 0.343 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.245 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.82 # between front wheel center and rear wheel center
    wheel_tread: 1.61 # between left wheel center and right wheel center
    front_overhang: 1.01 # between front wheel center and vehicle front
    rear_overhang: 1.06 # between rear wheel center and vehicle rear
    left_overhang: 0.15 # between left wheel center and vehicle left
    right_overhang: 0.15 # between right wheel center and vehicle right
    vehicle_height: 1.58
    max_steer_angle: 0.66 # [rad]
